  SET TERM ^ ;
  CREATE OR ALTER TRIGGER ADD_ESTOQUE_PRODUTO_ANIMAL FOR MOVI_PRODUTO
    ACTIVE
    BEFORE INSERT
    POSITION 0
  AS
  BEGIN
    IF (NEW.TIPO = 'E') then
     UPDATE ANIMAL A SET A.ESTOQUE = A.ESTOQUE + NEW.QUANTIDADE WHERE (NEW.ID_ANIMAL = A.ID);
   IF (NEW.TIPO = 'E') then
     UPDATE PRODUTO P SET P.ESTOQUE = P.ESTOQUE + NEW.QUANTIDADE WHERE (NEW.ID_PRODUTO = P.ID);
     
   IF (NEW.TIPO = 'S') then
    UPDATE ANIMAL A SET A.ESTOQUE = A.ESTOQUE - NEW.QUANTIDADE WHERE (NEW.ID_ANIMAL = A.ID);
   IF (NEW.TIPO = 'S') then
    UPDATE PRODUTO P SET P.ESTOQUE = P.ESTOQUE - NEW.QUANTIDADE WHERE (NEW.ID_PRODUTO = P.ID);
  END^
  SET TERM; ^