/*
--- Versao 2.0.0 ---
- Faz verificação de bloqueio do sistema (10/02/2022 - RS)

*/

INSERT INTO VERSAO VALUES(7, '02/10/2022', 'Versao 2.0');

ALTER TABLE CONFIGURACAO ADD BASE VARCHAR(2); /* SB - SISTEMA BLOQUEADO (LIBERADO ATE A DATA_BASE) / SL - SISTEMA LIBERADO */
UPDATE CONFIGURACAO SET BASE = 'SB';
ALTER TABLE CONFIGURACAO ADD DATA_BASE DATE;
UPDATE CONFIGURACAO SET DATA_BASE = '02/01/2022';