SET TERM ^ ;
  CREATE OR ALTER TRIGGER REMOVE_ESTOQUE_PRODUTO_ANIMAL FOR MOVI_PRODUTO
    ACTIVE
    BEFORE DELETE
    POSITION 0
  AS
  BEGIN
    IF (OLD.TIPO = 'E') then
     UPDATE ANIMAL A SET A.ESTOQUE = A.ESTOQUE - OLD.QUANTIDADE WHERE (OLD.ID_ANIMAL = A.ID);
   IF (OLD.TIPO = 'E') then
     UPDATE PRODUTO P SET P.ESTOQUE = P.ESTOQUE - OLD.QUANTIDADE WHERE (OLD.ID_PRODUTO = P.ID);
     
   IF (OLD.TIPO = 'S') then
    UPDATE ANIMAL A SET A.ESTOQUE = A.ESTOQUE + OLD.QUANTIDADE WHERE (OLD.ID_ANIMAL = A.ID);
   IF (OLD.TIPO = 'S') then
    UPDATE PRODUTO P SET P.ESTOQUE = P.ESTOQUE + OLD.QUANTIDADE WHERE (OLD.ID_PRODUTO = P.ID);
  END^
  SET TERM; ^