/*
-- 1.3.0 --
- Criação da tabela empresa e campo CODEMPRESA nas tabelas (14/08/2018)

-- 1.3.1 --
- Opção para deletar inseminacao na tela de Confirmação (23/08/2018)

*/

INSERT INTO VERSAO VALUES(3, '08/14/2018', 'Versao 1.3');

Create table EMPRESA(
ID INTEGER NOT NULL PRIMARY KEY,
SITUACAO VARCHAR(10),
RAZAO_SOCIAL VARCHAR(150) NOT NULL,
CNPJ VARCHAR(20) NOT NULL
);
insert into AUTOINCRE values ('EMPRESA', 0);

ALTER TABLE USUARIO ADD CODEMPRESA INTEGER;
UPDATE USUARIO SET CODEMPRESA = 1;
ALTER TABLE SERVICO ADD CODEMPRESA INTEGER;
UPDATE SERVICO SET CODEMPRESA = 1;
ALTER TABLE PRODUTO ADD CODEMPRESA INTEGER;
UPDATE PRODUTO SET CODEMPRESA = 1;
ALTER TABLE VETERINARIO ADD CODEMPRESA INTEGER;
UPDATE VETERINARIO SET CODEMPRESA = 1;
ALTER TABLE PRODUTOR ADD CODEMPRESA INTEGER;
UPDATE PRODUTOR SET CODEMPRESA = 1;
ALTER TABLE INSEMINACAO ADD CODEMPRESA INTEGER;
UPDATE INSEMINACAO SET CODEMPRESA = 1;
ALTER TABLE ANIMAL ADD CODEMPRESA INTEGER;
UPDATE ANIMAL SET CODEMPRESA = 1;
ALTER TABLE CRIA ADD CODEMPRESA INTEGER;
UPDATE CRIA SET CODEMPRESA = 1;
ALTER TABLE CONFIGURACAO ADD CODEMPRESA INTEGER;
UPDATE CONFIGURACAO SET CODEMPRESA = 1;
ALTER TABLE MOVI_PRODUTO ADD CODEMPRESA INTEGER;
UPDATE MOVI_PRODUTO SET CODEMPRESA = 1;
