/*
----- 1.6.0 -----
- Grava Cria na mesma tabela de Animal (09/11/2018 - RS)
- Grava foto no banco de dados em campo blob (09/11/2018 - RS)
- Faz o calculo da idade da cria (09/11/2018 - RS)


*/

INSERT INTO VERSAO VALUES(6, '11/09/2018', 'Versao 1.6');


ALTER TABLE ANIMAL ADD TIPO VARCHAR(10);
UPDATE ANIMAL SET TIPO = 'Animal';
ALTER TABLE ANIMAL ADD PAI INTEGER;
ALTER TABLE ANIMAL ADD MAE INTEGER;
ALTER TABLE ANIMAL ADD DATA_NASCIMENTO DATE;
ALTER TABLE ANIMAL ADD IDADE VARCHAR(30);
ALTER TABLE ANIMAL ADD OBSERVACAO BLOB;
ALTER TABLE ANIMAL ADD FOTOANIMAL BLOB;
ALTER TABLE PRODUTOR ADD PROPRIEDADE VARCHAR(100);