/*CRIACAO DAS TABELAS*/
create table AUTOINCRE(
Tabela varchar(50) primary key not null,
Sequencia integer
);

create table USUARIO(
ID INTEGER PRIMARY KEY NOT NULL,
NOME VARCHAR(50),
SENHA VARCHAR(50)
);

create table SERVICO(
ID INTEGER PRIMARY KEY NOT NULL,
DESCRICAO VARCHAR(50),
SITUACAO VARCHAR(10),
VALOR DECIMAL(10,2),
ALTERACAO TIMESTAMP NOT NULL,
USUARIO INTEGER NOT NULL
);

CREATE TABLE PRODUTO(
ID INTEGER PRIMARY KEY NOT NULL,
DESCRICAO VARCHAR(50),
SITUACAO VARCHAR(10),
UNIDADE VARCHAR(5),
VALOR DECIMAL(10, 2),
ESTOQUE DECIMAL(10,2),
ALTERACAO TIMESTAMP NOT NULL,
USUARIO INTEGER NOT NULL
);

create table VETERINARIO(
ID INTEGER PRIMARY KEY NOT NULL, 
NOME VARCHAR(50) NOT NULL,
SITUACAO VARCHAR(10),
CPF VARCHAR(20),
CRMV INTEGER NOT NULL,
UF_CRMV VARCHAR(2) NOT NULL,
CEP VARCHAR(9),
LOGRADOURO VARCHAR(50),
NUMERO VARCHAR(15),
COMPLEMENTO VARCHAR(30),
UF VARCHAR(2),
CIDADE VARCHAR(30),
BAIRRO VARCHAR(30),
TELI VARCHAR(15),
TELII VARCHAR(15),
TELIII VARCHAR(15),
EMAIL VARCHAR(50),
ALTERACAO TIMESTAMP NOT NULL,
USUARIO INTEGER NOT NULL
);

create table PRODUTOR(
ID INTEGER PRIMARY KEY NOT NULL, 
NOME VARCHAR(50) NOT NULL,
SITUACAO VARCHAR(10),
CPF VARCHAR(20),
TIPO VARCHAR(1),
INSC_RURAL INTEGER,
CNPJ VARCHAR(20),
INSCEST INTEGER,
CEP VARCHAR(9),
LOGRADOURO VARCHAR(50),
NUMERO VARCHAR(15),
COMPLEMENTO VARCHAR(30),
UF VARCHAR(2),
CIDADE VARCHAR(30),
BAIRRO VARCHAR(30),
TELI VARCHAR(15),
TELII VARCHAR(15),
TELIII VARCHAR(15),
EMAIL VARCHAR(50),
CONTATO VARCHAR(50),
ALTERACAO TIMESTAMP NOT NULL,
USUARIO INTEGER NOT NULL
);

create table ANIMAL(
ID INTEGER PRIMARY KEY NOT NULL,
NOME VARCHAR(50),
IDENTIFICACAO integer,
SITUACAO VARCHAR(10),
SEXO VARCHAR(1),		/* M > MACHO / F > FEMEA */
PROPRIETARIO integer,
PELAGEM VARCHAR(50),
AD VARCHAR(50),
PD VARCHAR(50),
CABECA VARCHAR(50),
AE VARCHAR(50),
PE VARCHAR(50),
OUTRAS VARCHAR(50),
FOTO VARCHAR(500),
ESTOQUE DECIMAL(10,2),
ALTERACAO TIMESTAMP NOT NULL,
USUARIO INTEGER NOT NULL
);

create table CRIA(
ID INTEGER PRIMARY KEY NOT NULL,
NOME VARCHAR(50),
IDENTIFICACAO integer,
SITUACAO VARCHAR(10),
SEXO VARCHAR(1),		/* M > MACHO / F > FEMEA */
PROPRIETARIO integer,
DATA_NASCIMENTO DATE,
PAI INTEGER,
MAE INTEGER,
PELAGEM VARCHAR(50),
AD VARCHAR(50),
PD VARCHAR(50),
CABECA VARCHAR(50),
AE VARCHAR(50),
PE VARCHAR(50),
OUTRAS VARCHAR(50),
FOTO VARCHAR(500),
ALTERACAO TIMESTAMP NOT NULL,
USUARIO INTEGER NOT NULL
);

create table INSEMINACAO(
ID INTEGER PRIMARY KEY NOT NULL,
NUMERO VARCHAR(15),
DATA DATE,
ID_PRODUTOR INTEGER,
ID_VETERINARIO INTEGER,
ID_TOURO INTEGER,
OBSERVACAO BLOB,
FINALIZADA VARCHAR(1),
DT_FINALIZADA TIMESTAMP,
ALTERACAO TIMESTAMP NOT NULL,
USUARIO INTEGER NOT NULL
);

create table MOVI_INSEMINACAO(
ID INTEGER NOT NULL PRIMARY KEY,
ID_INSEMINACAO INTEGER NOT NULL,
ID_ANIMAL INTEGER NOT NULL,
ID_SERVICO INTEGER NOT NULL,
ID_PRODUTO INTEGER NOT NULL,
VLR_UNIT DECIMAL(10,2),
CONFIRMADA VARCHAR(1), /* A > ANALISE / S > SIM / N > NAO */
DATA_CONFIRMACAO DATE
);

create table CONFIGURACAO(
ID INTEGER NOT NULL PRIMARY KEY,
VETERINARIO_PADRAO INTEGER,
SERVICO_PADRAO INTEGER,
PRODUTO_INSEMINACAO INTEGER,
CAMINHO_FOTO VARCHAR(50),
ALTERACAO TIMESTAMP NOT NULL,
USUARIO INTEGER NOT NULL
);

create table MOVI_PRODUTO(
ID INTEGER NOT NULL PRIMARY KEY,
NUMERO VARCHAR(30),
DATA TIMESTAMP,
ID_PRODUTO INTEGER NOT NULL,
ID_ANIMAL INTEGER NOT NULL,
QUANTIDADE DECIMAL(10,2),
TIPO VARCHAR(1),
UNIDADE VARCHAR(5),
ALTERACAO TIMESTAMP NOT NULL,
USUARIO INTEGER NOT NULL
);


insert into AUTOINCRE values ('USUARIO',0);
insert into AUTOINCRE values ('SERVICO',0);
insert into AUTOINCRE values ('VETERINARIO',0);
insert into AUTOINCRE values ('PRODUTOR',0);
insert into AUTOINCRE values ('ANIMAL',0);
insert into AUTOINCRE values ('CRIA',0);
insert into AUTOINCRE values ('INSEMINACAO',0);
insert into AUTOINCRE values ('PRODUTO',0);
insert into AUTOINCRE values ('MOVI_INSEMINACAO',0);
insert into AUTOINCRE values ('MOVI_PRODUTO',0);

ALTER TABLE ANIMAL ADD CONSTRAINT FK_ID_PROPRIETARIO FOREIGN KEY (PROPRIETARIO) REFERENCES PRODUTOR (ID);
ALTER TABLE CRIA ADD CONSTRAINT FK_ID_PROPRIETARIO_CRIA FOREIGN KEY (PROPRIETARIO) REFERENCES PRODUTOR (ID);
ALTER TABLE CRIA ADD CONSTRAINT FK_ID_MAE FOREIGN KEY (MAE) REFERENCES ANIMAL (ID);

ALTER TABLE INSEMINACAO ADD CONSTRAINT FK_ID_PRODUTOR FOREIGN KEY (ID_PRODUTOR) REFERENCES PRODUTOR (ID);
ALTER TABLE INSEMINACAO ADD CONSTRAINT FK_ID_VETERINARIO FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO (ID);
ALTER TABLE INSEMINACAO ADD CONSTRAINT FK_ID_TOURO FOREIGN KEY (ID_TOURO) REFERENCES ANIMAL (ID);

ALTER TABLE MOVI_INSEMINACAO ADD CONSTRAINT FK_COD_SERV FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO (ID);
ALTER TABLE MOVI_INSEMINACAO ADD CONSTRAINT FK_COD_ANI FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL (ID);
ALTER TABLE MOVI_INSEMINACAO ADD CONSTRAINT FK_ID_INSEMINACAO FOREIGN KEY (ID_INSEMINACAO) REFERENCES INSEMINACAO (ID) on delete cascade;

ALTER TABLE MOVI_PRODUTO ADD CONSTRAINT FK_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID);






